# Generated by Django 3.1.1 on 2021-01-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardigan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=89)),
                ('description', models.CharField(max_length=144)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
