# Generated by Django 3.1.4 on 2021-01-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_cardigan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=21)),
            ],
        ),
    ]
