# Generated by Django 3.1.4 on 2021-01-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0004_auto_20210111_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardigan',
            name='description',
            field=models.CharField(blank=True, max_length=233),
        ),
        migrations.AddField(
            model_name='cardigan',
            name='fob',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cardigan',
            name='gauge',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cardigan',
            name='moq',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cardigan',
            name='size',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cardigan',
            name='weight',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='cardigan',
            name='composition',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
