# Generated by Django 3.1.4 on 2021-01-11 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0006_pullover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=144)),
                ('description', models.CharField(blank=True, max_length=233)),
                ('composition', models.CharField(blank=True, max_length=64)),
                ('gauge', models.CharField(blank=True, max_length=32)),
                ('size', models.CharField(blank=True, max_length=32)),
                ('weight', models.CharField(blank=True, max_length=32)),
                ('moq', models.CharField(blank=True, max_length=32)),
                ('fob', models.CharField(blank=True, max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vest', to='kids.category')),
            ],
        ),
    ]
