# Generated by Django 3.1.4 on 2021-01-12 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0007_vest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
