# Generated by Django 3.1.5 on 2021-01-30 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardigan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=34)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.category')),
            ],
        ),
    ]
