# Generated by Django 3.1.1 on 2021-02-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardigan',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='kids/cardigan'),
        ),
        migrations.AddField(
            model_name='pullover',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='kids/pullover'),
        ),
        migrations.AddField(
            model_name='vest',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='kids/vest'),
        ),
    ]
